### ISSUE TITLE
Basic interface

### ISSUE THREAD

**Issue by michalkr52** [autonomous-vehicle-sim/Simulator#11]
Proste, uniwersalne obiekty do:
- przedstawienia informacji na ekranie podczas jazdy
- dostosowania dowolnych właściwości

Do tego dostosować Canvas interfejsu żeby był jednolicie wyświetlany na różnych rozdzielczościach/rozmiarach ekranów.

**Comment by lukrzak** [comment]
Lgtm

**Comment by michalkr52** [comment]
Zaimplementowałem interfejs, na razie bez widoku planszy (minimapa). 

https://github.com/autonomous-vehicle-sim/Simulator/commit/da14527636d5fc6f9bc1af8f17776a66c6e6971d

**Comment by michalkr52** [comment]
https://github.com/autonomous-vehicle-sim/Simulator/pull/16
