### ISSUE TITLE
Translate Kanban and issues to English

### ISSUE THREAD

**Issue by kobryl** [autonomous-vehicle-sim/Simulator#17]
- [x] translate Kanban items and repository issues to English
- [x] Unify issue and Kanban numbering

**Comment by kobryl** [comment]
Removed numbering from Kanban table items

**Comment by kobryl** [comment]
Translated all titles of the issues and Kanban table items, my comments on issues, and some of the descriptions in the Kanban table. Rest of the comments and description needs to be translated by authors. (#18)

**Comment by michalkr52** [comment]
done with my part
