### ISSUE TITLE
Create first project documents

### ISSUE THREAD

**Issue by kobryl** [autonomous-vehicle-sim/Simulator#2]
- Create documents @kobryl
    - [x] IoP
    - [x] HiSW
    - ~~[ ] DTP~~
    - ~~[ ] Plakat~~ (moved to separate issues)

- Handle deadlines and contact with coordinator @lukrzak

**Comment by lukrzak** [comment]
Podejdę do niego 08.11 z HiSW i poproszę o potwierdzenie

**Comment by kobryl** [comment]
HiSW punkty 4.2 i 4.3 do ustalenia z opiekunem

**Comment by kobryl** [comment]
Wysłałem maila do dr Gajewskiego i czekam na odpowiedź

**Comment by kobryl** [comment]
czekam na odpowiedź do końca tygodnia - jak nie da to robię na wyczucie
