### ISSUE TITLE
#6 Stworzenie modelu planszy i łazika

### ISSUE THREAD

**Issue by kobryl** [autonomous-vehicle-sim/Simulator#4]
- płaska plansza z zygzakiem czarnym
- łazik w postaci kwadrata z kołami i kamerami
- zapisywanie zrzutów ekranu

**Comment by Shairys** [comment]
System nagrywania kamer + podstawowy model pojazdu i podłogi (tutaj auto wypadałoby zrobić porządnie w blenderze, do podłogi mogę napisać generator na podstawie wave function collapse ale to nie w tym tygodniu)
Dokładniej opisane w https://github.com/autonomous-vehicle-sim/Simulator/commit/31b48b1dd64966773e8d5162b647aa8ffa54f401
