### ISSUE TITLE
Implement better physics

### ISSUE THREAD

**Issue by michalkr52** [autonomous-vehicle-sim/Simulator#41]

**Comment by michalkr52** [comment]
https://github.com/autonomous-vehicle-sim/Simulator/commit/2d4bef8d9e5a184923b4c9ee5ee25473ceeefc2a

**Comment by michalkr52** [comment]
Our model should now behave similarly to a real RC car.

https://github.com/autonomous-vehicle-sim/Simulator/commit/bc72e1d15e169036ee0bb5d73d131f475171460f

**Comment by kobryl** [comment]
Closed as done with https://github.com/autonomous-vehicle-sim/Simulator/commit/bc72e1d15e169036ee0bb5d73d131f475171460f
